version: "3.7"

services:

  elm:
    build:
      context: ./front
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    command: elm-app start
    depends_on:
      - go

  go:
    build:
      context: ./back
    restart: always
    depends_on:
      - db
    volumes:
      - ./back/config.yaml:/config.yaml
      - ./uploads:/uploads
    ports:
      - 1323:80

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: elmbum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
      - ./back/migrations/1_init_schema.sql:/docker-entrypoint-initdb.d/1_init_schema.sql
    ports:
      - 5432:5432

volumes:
  db-data: