name: reviewdog
on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/reviewdog.yml"
      - "back/**"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/reviewdog.yml"
      - "back/**"

env:
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  golangci-lint-all-in-one:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint (All-In-One config)
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          level: "warning"
          reporter: "github-check"
