name: reviewdog
on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/reviewdog.yml"
      - "back/**"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/reviewdog.yml"
      - "back/**"

env:
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  golangci-lint-all-in-one:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        env:
          RUNNER_TEMP: /tmp
        with:
          go-version: '^1.14'

      - name: Download golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
          $(go env GOPATH)/bin/golangci-lint version

      - name: Run golangci-lint (All-In-One config)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd back
          $(go env GOPATH)/bin/golangci-lint run --out-format=github-actions --enable-all --exclude-use-default=false ./...
